name: Release Service

on:
  push:
    tags:
      - 'v*.*'

jobs:
  ReleasePackage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Prepare StartOS SDK
        uses: Start9Labs/sdk@v1

      - name: Checkout services repository
        uses: actions/checkout@v3

      - name: Build the service package
        run: |
          git submodule update --init --recursive
          start-sdk init
          make

      - name: Setting package ID and title from the manifest
        id: package
        run: |
          echo "::set-output name=package_id::$(yq -oy ".id" manifest.*)"
          echo "::set-output name=package_title::$(yq -oy ".title" manifest.*)"
        shell: bash

      - name: Generate sha256 checksum
        run: |
          PACKAGE_ID=${{ steps.package.outputs.package_id }}
          sha256sum ${PACKAGE_ID}.s9pk > ${PACKAGE_ID}.s9pk.sha256
        shell: bash

      - name: Generate changelog
        run: |
          PACKAGE_ID=${{ steps.package.outputs.package_id }}
          echo "## What's Changed" > change-log.txt
          yq e '.release-notes' manifest.yaml >> change-log.txt
          echo "## SHA256 Hash" >> change-log.txt
          echo '```' >> change-log.txt
          sha256sum ${PACKAGE_ID}.s9pk >> change-log.txt
          echo '```' >> change-log.txt
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.package.outputs.package_title }} ${{ github.ref_name }}
          prerelease: true
          body_path: change-log.txt
          files: |
            ./${{ steps.package.outputs.package_id }}.s9pk
            ./${{ steps.package.outputs.package_id }}.s9pk.sha256

      - name: Publish to Registry
        env:
          S9USER: ${{ secrets.S9USER }}
          S9PASS: ${{ secrets.S9PASS }}
          S9REGISTRY: ${{ secrets.S9REGISTRY }}
        run: |
          if [[ -z "$S9USER" || -z "$S9PASS" || -z "$S9REGISTRY" ]]; then
            echo "Publish skipped: missing registry credentials."
          else
            start-sdk publish https://$S9USER:$S9PASS@$S9REGISTRY ${{ steps.package.outputs.package_id }}.s9pk
          fi
