name: Release Service

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  BuildPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare StartOS SDK
        uses: Start9Labs/sdk@v1

      - name: Checkout services repository
        uses: actions/checkout@v3

      - name: Build the service package
        run: |
          git submodule update --init --recursive
          start-sdk init
          make

      - name: Generate sha256 checksum
        run: |
          sha256sum bitcoind.s9pk > bitcoind.s9pk.sha256

      - name: Generate changelog
        run: |
          echo "## What's Changed" > change-log.txt
          yq e '.release-notes' manifest.yaml >> change-log.txt
          echo "## SHA256 Hash" >> change-log.txt
          echo '```' >> change-log.txt
          sha256sum bitcoind.s9pk >> change-log.txt
          echo '```' >> change-log.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Bitcoin Core ${{ github.ref_name }}
          body_path: change-log.txt
          files: |
            bitcoind.s9pk
            bitcoind.s9pk.sha256
